### ISSUE TITLE
[Feature] Add support for `arkade install shlink`

### ISSUE THREAD

**Issue by blaisep-vgs** [neilfrndes/shlink-helm-chart#1]
@neilfrndes , this is awesome, thank you.
I ran into a few problems so I don't have it fully working yet. When I do, I will look into adding it to https://github.com/alexellis/arkade , if that is ok with you.

**Comment by neilfrndes** [comment]
Let me know what problems you ran into, happy to help you debug.

Yes, its okay to link this repo to arkade.

**Comment by blaisep-vgs** [comment]
Hi @neilfrndes ,
Just a heads up that I keep getting this error:

```
$ helm install shlink-vgs-dev ./shlink   --set "ingress.enabled=true"  --set "env.SHORT_DOMAIN_HOST=go.vgs"

Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false}],"im|..., bigger context ...|iadb"}}},{"name":"ANONYMIZE_REMOTE_ADDR","value":false}],"image":"shlinkio/shlink:2.2.1","imagePullP|..

Helm version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
Digital ocean kubernetes 1.17.5-do.0
```

Do you have any suggestions?
It's my personal cluster and I'm happy to give you access.

**Comment by blaisep-vgs** [comment]
Oh!
It seems to work if I edit values.yaml and change:
`ANONYMIZE_REMOTE_ADDR: none`
instead of false
